@WebApiLearning.Server_HostAddress = http://localhost:5134

GET {{WebApiLearning.Server_HostAddress}}/GameItems
Accept: application/json

###

GET {{WebApiLearning.Server_HostAddress}}/GameItems/da7ece1c-a878-46e5-9710-c60c5a7139a1
Accept: application/json

###

POST {{WebApiLearning.Server_HostAddress}}/GameItems
Content-Type: application/json

{
  "Name": "Premium Potion",
  "Price": 10.99
}

###

PUT {{WebApiLearning.Server_HostAddress}}/GameItems/da7ece1c-a878-46e5-9710-c60c5a7139a1
Content-Type: application/json

{
  "Name": "Super Potion",
  "Price": 20.99
}

###


